name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 3 * * 0' # every Sunday at 3am

env:
  CI: true

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    # needs: [tests]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: volta-cli/action@v4
      - run: yarn install

      - name: Release
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
